import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';

class DatabaseHandler {
  static final DatabaseHandler _databaseHandler = DatabaseHandler._internal();

  factory DatabaseHandler() {
    return _databaseHandler;
  }

  DatabaseHandler._internal();

  Database? database;

  Future<void> initDb() async {
    database = await openDatabase(
        join(await getDatabasesPath(), 'message_database.db'),
        version: _migrationScripts.length + 1,
        onCreate: (Database db, int version) async {
          _initialScript.forEach((script) async => await db.execute(script));
          _migrationScripts.forEach((script) async => await db.execute(script));
        },
        onUpgrade: (Database db, int oldVersion, int newVersion) async {
          for (var i = oldVersion - 1; i < newVersion - 1; i++) {
            await db.execute(_migrationScripts[i]);
          }
        }
    );
  }

  // Future<void> deleteDatabase() async {
  //   var databasesPath = await getDatabasesPath();
  //   String path = join(databasesPath, 'message_database.db');
  //   await databaseFactory.deleteDatabase(path);
  // }

  static final _initialScript = [
    '''
      PRAGMA foreign_keys = ON;
    ''',
    '''
      CREATE TABLE Utilisateur (
        id TEXT PRIMARY KEY,
        nom TEXT NOT NULL
      );
    ''',
    '''
      CREATE TABLE Role (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        id_utilisateur TEXT,
        role TEXT NOT NULL,
        FOREIGN KEY(id_utilisateur) REFERENCES Utilisateur(id)
      );
    ''',
    '''
      INSERT INTO Utilisateur (id, nom)
      VALUES 
      ('auth0|657675b1e94488fb5f7915c3', 'admin@admin.com'),
      ('auth0|65767609ef593280157c9b1c', 'test@test.com');
 ''',
    '''
      CREATE TABLE Recipe (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT,
        type TEXT,
        description TEXT,
        imagePath TEXT,
        idUser TEXT
      );
    ''',
    '''
      CREATE TABLE Ingredients (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT,
        type TEXT
      );
    ''',
    '''
    CREATE TABLE RecipesIngredients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    recipeId INTEGER,  
    name TEXT,
    quantity TEXT,
    FOREIGN KEY (recipeId) REFERENCES Recipe (id)

);
    '''
  ];

  static final _migrationScripts = [
    '''
      INSERT INTO Role (id_utilisateur, role)
      VALUES ('auth0|657675b1e94488fb5f7915c3', 'admin')      
    '''
    ,
    '''
      INSERT INTO Ingredients (name, type)
      VALUES
      ('Abricot', 'Fruit'),
  ('Ananas', 'Fruit'),
  ('Avocat', 'Fruit'),
  ('Banane', 'Fruit'),
  ('Cassis', 'Fruit'),
  ('Cerise', 'Fruit'),
  ('Citron', 'Fruit'),
  ('Clémentine', 'Fruit'),
  ('Coing', 'Fruit'),
  ('Figue', 'Fruit'),
  ('Fraise', 'Fruit'),
  ('Framboise', 'Fruit'),
  ('Fruit de la passion', 'Fruit'),
  ('Grenade', 'Fruit'),
  ('Groseille', 'Fruit'),
  ('Kaki', 'Fruit'),
  ('Kiwi', 'Fruit'),
  ('Litchi', 'Fruit'),
  ('Mangue', 'Fruit'),
  ('Melon', 'Fruit'),
  ('Mûre', 'Fruit'),
  ('Myrtille', 'Fruit'),
  ('Nectarine', 'Fruit'),
  ('Orange', 'Fruit'),
  ('Papaye', 'Fruit'),
  ('Pastèque', 'Fruit'),
  ('Pêche', 'Fruit'),
  ('Pépino', 'Fruit'),
  ('Pomelo', 'Fruit'),
  ('Pomme', 'Fruit'),
  ('Poire', 'Fruit'),
  ('Prune', 'Fruit'),
  ('Raisin', 'Fruit'),
  ('Rhubarbe', 'Fruit'),
  ('Surelle', 'Fruit'),
  ('Tomate', 'Fruit'),
  ('Vigne', 'Fruit'),
  ('Yuzu', 'Fruit'),
  ('Anone', 'Fruit'),
  ('Baie de goji', 'Fruit'),
  ('Carambole', 'Fruit'),
  ('Châtaigne', 'Fruit'),
  ('Goyave', 'Fruit'),
  ('Grenadille', 'Fruit'),
  ('Jacquier', 'Fruit'),
  ('Kumquat', 'Fruit'),
  ('Mangoustan', 'Fruit'),
  ('Pamplemousse', 'Fruit'),
  ('Physalis', 'Fruit'),
  ('Sapote', 'Fruit'),
  ('Sureau', 'Fruit'),
  ('Artichaut', 'Légume'),
  ('Aubergine', 'Légume'),
  ('Asperge', 'Légume'),
  ('Betterave', 'Légume'),
  ('Bok choy', 'Légume'),
  ('Brocoli', 'Légume'),
  ('Carotte', 'Légume'),
  ('Céleri', 'Légume'),
  ('Champignon', 'Légume'),
  ('Chou de Bruxelles', 'Légume'),
  ('Chou frisé', 'Légume'),
  ('Chou-rave', 'Légume'),
  ('Chou-fleur', 'Légume'),
  ('Concombre', 'Légume'),
  ('Courge', 'Légume'),
  ('Courgette', 'Légume'),
  ('Cresson', 'Légume'),
  ('Endive', 'Légume'),
  ('Épinard', 'Légume'),
  ('Fenouil', 'Légume'),
  ('Haricot vert', 'Légume'),
  ('Jicama', 'Légume'),
  ('Kale', 'Légume'),
  ('Laitue', 'Légume'),
  ('Mâche', 'Légume'),
  ('Maïs', 'Légume'),
  ('Navet', 'Légume'),
  ('Oignon', 'Légume'),
  ('Panais', 'Légume'),
  ('Pâtisson', 'Légume'),
  ('Persil', 'Légume'),
  ('Petit pois', 'Légume'),
  ('Poireau', 'Légume'),
  ('Poivron', 'Légume'),
  ('Pomme de terre', 'Légume'),
  ('Radis', 'Légume'),
  ('Rutabaga', 'Légume'),
  ('Salsifis', 'Légume'),
  ('Scarole', 'Légume'),
  ('Seigle', 'Légume'),
  ('Tomate', 'Légume'),
  ('Vitellote', 'Légume'),
  ('Yam', 'Légume'),
  ('Zucchini', 'Légume'),
  ('Bambou', 'Légume'),
  ('Coriandre', 'Légume'),
  ('Cornichon', 'Légume'),
  ('Daikon', 'Légume'),
  ('Échalote', 'Légume'),
  ('Gingembre', 'Légume'),
  ('Haricot mungo', 'Légume'),
  ('Haricot rouge', 'Légume'),
  ('Lentille', 'Légume'),
  ('Moutarde', 'Légume'),
  ('Poivron rouge', 'Légume'),
  ('Poivron vert', 'Légume'),
  ('Poivron jaune', 'Légume'),
  ('Poivron orange', 'Légume'),
  ('Safran', 'Légume'),
  ('Sarriette', 'Légume'),
  ('Soja', 'Légume'),
  ('Sucrine', 'Légume'),
  ('Tamarin', 'Légume'),
  ('Thym', 'Légume'),
  ('Topinambour', 'Légume'),
  ('Wasabi', 'Légume'),
  ('Zébu', 'Légume'),
  ('Blette', 'Légume'),
  ('Butternut', 'Légume'),
  ('Cébette', 'Légume'),
  ('Cèpe', 'Légume'),
  ('Ciboulette', 'Légume'),
  ('Cornille', 'Légume'),
  ('Cynorhodon', 'Légume'),
  ('Échalote grise', 'Légume'),
  ('Fève', 'Légume'),
  ('Fraise des bois', 'Légume'),
  ('Fritillaire', 'Légume'),
  ('Groseille à maquereau', 'Légume'),
  ('Gros plant', 'Légume'),
  ('Haricot', 'Légume'),
  ('Haricot tarbais', 'Légume'),
  ('Igname', 'Légume'),
  ('Légume oublié', 'Légume'),
  ('Madère', 'Légume'),
  ('Maïs doux', 'Légume'),
  ('Mogette', 'Légume'),
  ('Nopal', 'Légume'),
  ('Origan', 'Légume'),
  ('Périgueux', 'Légume'),
  ('Poivron doux', 'Légume'),
  ('Poivron vert doux', 'Légume'),
  ('Agneau', 'Viande'),
  ('Autruche', 'Viande'),
  ('Bœuf', 'Viande'),
  ('Canard', 'Viande'),
  ('Cheval', 'Viande'),
  ('Chevreuil', 'Viande'),
  ('Cochon', 'Viande'),
  ('Coq', 'Viande'),
  ('Cordon bleu', 'Viande'),
  ('Dinde', 'Viande'),
  ('Émeu', 'Viande'),
  ('Escalope', 'Viande'),
  ('Foie gras', 'Viande'),
  ('Gibier', 'Viande'),
  ('Gigot d''agneau', 'Viande'),
  ('Gigot de chevreuil', 'Viande'),
  ('Gigot de mouton', 'Viande'),
  ('Gigot d''oie', 'Viande'),
  ('Hamburger', 'Viande'),
  ('Jambon', 'Viande'),
  ('Jarret de porc', 'Viande'),
  ('Lamb', 'Viande'),
  ('Lapin', 'Viande'),
  ('Lard', 'Viande'),
  ('Merguez', 'Viande'),
  ('Mouton', 'Viande'),
  ('Pâté', 'Viande'),
  ('Pied de porc', 'Viande'),
  ('Pigeon', 'Viande'),
  ('Porc', 'Viande'),
  ('Poulet', 'Viande'),
  ('Ragoût', 'Viande'),
  ('Rillettes', 'Viande'),
  ('Rognon', 'Viande'),
  ('Rôti de bœuf', 'Viande'),
  ('Rôti de dinde', 'Viande'),
  ('Rôti de porc', 'Viande'),
  ('Saucisse', 'Viande'),
  ('Saucisson', 'Viande'),
  ('Souris d''agneau', 'Viande'),
  ('Souris de porc', 'Viande'),
  ('Steak', 'Viande'),
  ('Steak haché', 'Viande'),
  ('Steak de bœuf', 'Viande'),
  ('Steak de cheval', 'Viande'),
  ('Steak de dinde', 'Viande'),
  ('Steak de kangourou', 'Viande'),
  ('Steak de porc', 'Viande'),
  ('Tripes', 'Viande'),
  ('Veau', 'Viande'),
  ('Volaille', 'Viande'),
  ('Wok de poulet', 'Viande'),
  ('Ail', 'Épice'),
  ('Aneth', 'Épice'),
  ('Anis étoilé', 'Épice'),
  ('Asafoetida', 'Épice'),
  ('Badiane', 'Épice'),
  ('Baie de genévrier', 'Épice'),
  ('Cardamome', 'Épice'),
  ('Cannelle', 'Épice'),
  ('Carvi', 'Épice'),
  ('Clou de girofle', 'Épice'),
  ('Coriandre', 'Épice'),
  ('Cumin', 'Épice'),
  ('Curcuma', 'Épice'),
  ('Fenouil', 'Épice'),
  ('Fenugrec', 'Épice'),
  ('Galanga', 'Épice'),
  ('Gingembre', 'Épice'),
  ('Graines de moutarde', 'Épice'),
  ('Graines de sésame', 'Épice'),
  ('Herbe de Provence', 'Épice'),
  ('Laurier', 'Épice'),
  ('Muscade', 'Épice'),
  ('Origan', 'Épice'),
  ('Paprika', 'Épice'),
  ('Piment de Cayenne', 'Épice'),
  ('Piment de la Jamaïque', 'Épice'),
  ('Piment de l''Espelette', 'Épice'),
  ('Poivre blanc', 'Épice'),
  ('Poivre noir', 'Épice'),
  ('Poivre de Cayenne', 'Épice'),
  ('Poivre de Sichuan', 'Épice'),
  ('Quatre-épices', 'Épice'),
  ('Réglisse', 'Épice'),
  ('Ras el hanout', 'Épice'),
  ('Romarin', 'Épice'),
  ('Safran', 'Épice'),
  ('Sauge', 'Épice'),
  ('Sel', 'Épice'),
  ('Sumac', 'Épice'),
  ('Tamarin', 'Épice'),
  ('Thym', 'Épice'),
  ('Vanille', 'Épice'),
  ('Wasabi', 'Épice'),
  ('Zeste de citron', 'Épice'),
  ('Zeste d''orange', 'Épice'),
  ('Zeste de lime', 'Épice'),
  ('Zeste de pamplemousse', 'Épice'),
  ('Zeste de citron vert', 'Épice'),
  ('Zeste de bergamote', 'Épice'),
  ('Zeste de cédrat', 'Épice'),
  ('Vinaigre balsamique', 'Vinaigre'),
  ('Vinaigre blanc', 'Vinaigre'),
  ('Vinaigre de cidre', 'Vinaigre'),
  ('Vinaigre de malt', 'Vinaigre'),
  ('Vinaigre de riz', 'Vinaigre'),
  ('Vinaigre de vin rouge', 'Vinaigre'),
  ('Vinaigre de vin blanc', 'Vinaigre'),
  ('Vinaigre de Xérès', 'Vinaigre'),
  ('Vinaigre de framboise', 'Vinaigre'),
  ('Vinaigre de grenade', 'Vinaigre'),
  ('Vinaigre de miel', 'Vinaigre'),
  ('Vinaigre de noix', 'Vinaigre'),
  ('Vinaigre de poire', 'Vinaigre'),
  ('Vinaigre de tomate', 'Vinaigre'),
  ('Vinaigre de vin de Champagne', 'Vinaigre'),
  ('Vinaigre de vin de riz', 'Vinaigre'),
  ('Vinaigre de cidre de pomme', 'Vinaigre'),
  ('Vinaigre de figue', 'Vinaigre'),
  ('Vinaigre de mangue', 'Vinaigre'),
  ('Sauce barbecue', 'Sauce'),
  ('Sauce béarnaise', 'Sauce'),
  ('Sauce cocktail', 'Sauce'),
  ('Sauce hollandaise', 'Sauce'),
  ('Sauce tomate', 'Sauce'),
  ('Sauce à l''ail', 'Sauce'),
  ('Sauce à l''aneth', 'Sauce'),
  ('Sauce aux champignons', 'Sauce'),
  ('Sauce aux poivres', 'Sauce'),
  ('Sauce aux canneberges', 'Sauce'),
  ('Sauce aux airelles', 'Sauce'),
  ('Sauce teriyaki', 'Sauce'),
  ('Sauce hoisin', 'Sauce'),
  ('Sauce piquante', 'Sauce'),
  ('Sauce chimichurri', 'Sauce'),
  ('Sauce pesto', 'Sauce'),
  ('Sauce tartare', 'Sauce'),
  ('Sauce Worcestershire', 'Sauce'),
  ('Sauce aigre-douce', 'Sauce'),
  ('Sauce soja', 'Sauce'),
  ('Sauce tzatziki', 'Sauce'),
  ('Sauce aux câpres', 'Sauce'),
  ('Sauce moutarde', 'Sauce'),
  ('Sauce sriracha', 'Sauce'),
  ('Sauce aux agrumes', 'Sauce'),
 ('Farine de blé', 'Farine'),
  ('Farine de maïs', 'Farine'),
  ('Farine de seigle', 'Farine'),
  ('Farine d''épeautre', 'Farine'),
  ('Farine de riz', 'Farine'),
  ('Farine de sarrasin', 'Farine'),
  ('Farine d''avoine', 'Farine'),
  ('Farine de pois chiche', 'Farine'),
  ('Farine de quinoa', 'Farine'),
  ('Farine de noix de coco', 'Farine'),
  ('Farine de teff', 'Farine'),
  ('Farine de manioc', 'Farine'),
  ('Farine de millet', 'Farine'),
  ('Farine de châtaigne', 'Farine'),
  ('Farine d''amande', 'Farine'),
  ('Moutarde de Dijon', 'Moutarde'),
  ('Moutarde à l''ancienne', 'Moutarde'),
  ('Moutarde de Meaux', 'Moutarde'),
  ('Moutarde de Bénichon', 'Moutarde'),
  ('Moutarde au miel', 'Moutarde'),
  ('Moutarde au curry', 'Moutarde'),
  ('Moutarde au vin blanc', 'Moutarde'),
  ('Moutarde au vin rouge', 'Moutarde'),
  ('Moutarde à l''estragon', 'Moutarde'),
  ('Moutarde au poivre vert', 'Moutarde'),
  ('Moutarde au miel et au romarin', 'Moutarde'),
  ('Moutarde à l''ail', 'Moutarde'),
  ('Moutarde aux herbes de Provence', 'Moutarde'),
  ('Moutarde à l''érable', 'Moutarde'),
  ('Moutarde au raifort', 'Moutarde'),
  ('Moutarde à l''ancienne à l''échalote', 'Moutarde'),
  ('Moutarde au piment d''Espelette', 'Moutarde'),
  ('Moutarde au citron', 'Moutarde'),
  ('Moutarde au tandoori', 'Moutarde'),
  ('Moutarde au wasabi', 'Moutarde'),
  ('Spaghetti', 'Pâtes'),
  ('Fettuccine', 'Pâtes'),
  ('Linguine', 'Pâtes'),
  ('Penne', 'Pâtes'),
  ('Rigatoni', 'Pâtes'),
  ('Tagliatelle', 'Pâtes'),
  ('Orecchiette', 'Pâtes'),
  ('Farfalle', 'Pâtes'),
  ('Conchiglie', 'Pâtes'),
  ('Fusilli', 'Pâtes'),
  ('Lasagne', 'Pâtes'),
  ('Pappardelle', 'Pâtes'),
  ('Capellini', 'Pâtes'),
  ('Cavatappi', 'Pâtes'),
  ('Tortellini', 'Pâtes'),
  ('Ravioli', 'Pâtes'),
  ('Gnocchi', 'Pâtes'),
  ('Macaroni', 'Pâtes'),
  ('Paccheri', 'Pâtes'),
  ('Ziti', 'Pâtes'),
  ('Poudre de cacao', 'Poudre'),
  ('Poudre de curry', 'Poudre'),
  ('Poudre de chili', 'Poudre'),
  ('Poudre de cannelle', 'Poudre'),
  ('Poudre de cumin', 'Poudre'),
  ('Poudre de coriandre', 'Poudre'),
  ('Poudre de paprika', 'Poudre'),
  ('Poudre de gingembre', 'Poudre'),
  ('Poudre de curcuma', 'Poudre'),
  ('Poudre de poivre', 'Poudre'),
  ('Poudre de vanille', 'Poudre'),
  ('Poudre de noix de muscade', 'Poudre'),
  ('Poudre d''ail', 'Poudre'),
  ('Poudre d''oignon', 'Poudre'),
  ('Poudre de cardamome', 'Poudre'),
  ('Poudre de clou de girofle', 'Poudre'),
  ('Poudre de moutarde', 'Poudre'),
  ('Poudre de cari', 'Poudre'),
  ('Poudre de garam masala', 'Poudre'),
  ('Huile d''olive', 'Huile'),
  ('Huile de canola', 'Huile'),
  ('Huile de tournesol', 'Huile'),
  ('Huile de maïs', 'Huile'),
  ('Huile de sésame', 'Huile'),
  ('Huile d''arachide', 'Huile'),
  ('Huile de noix', 'Huile'),
  ('Huile de noisette', 'Huile'),
  ('Huile d''avocat', 'Huile'),
  ('Huile de pépins de raisin', 'Huile'),
  ('Huile de coco', 'Huile'),
  ('Huile de lin', 'Huile'),
  ('Huile d''amande', 'Huile'),
  ('Huile de colza', 'Huile'),
  ('Huile de chanvre', 'Huile'),
  ('Huile de palme', 'Huile'),
  ('Huile de pistache', 'Huile'),
  ('Huile de carthame', 'Huile'),
  ('Huile de cameline', 'Huile'),
  ('Huile de bourrache', 'Huile'),
  ('Huile de tournesol haute oleique', 'Huile'),
  ('Huile de citrouille', 'Huile'),
  ('Huile de périlla', 'Huile'),
  ('Huile de macadamia', 'Huile'),
  ('Brie', 'Fromage'),
  ('Camembert', 'Fromage'),
  ('Roquefort', 'Fromage'),
  ('Gruyère', 'Fromage'),
  ('Emmental', 'Fromage'),
  ('Cheddar', 'Fromage'),
  ('Mozzarella', 'Fromage'),
  ('Parmesan', 'Fromage'),
  ('Feta', 'Fromage'),
  ('Gorgonzola', 'Fromage'),
  ('Edam', 'Fromage'),
  ('Gouda', 'Fromage'),
  ('Bleu d''Auvergne', 'Fromage'),
  ('Manchego', 'Fromage'),
  ('Stilton', 'Fromage'),
  ('Ricotta', 'Fromage'),
  ('Chevre', 'Fromage'),
  ('Munster', 'Fromage'),
  ('Gouda fumé', 'Fromage'),
  ('Gouda au cumin', 'Fromage'),
  ('Mimolette', 'Fromage'),
  ('Comté', 'Fromage'),
  ('Raclette', 'Fromage'),
  ('Emmental suisse', 'Fromage'),
  ('Taleggio', 'Fromage'),
  ('Fontina', 'Fromage'),
  ('Pepper Jack', 'Fromage'),
  ('Provolone', 'Fromage'),
  ('Fromage de chèvre frais', 'Fromage'),
  ('Fromage de chèvre affiné', 'Fromage'),
  ('Gouda jeune', 'Fromage'),
  ('Gouda vieux', 'Fromage'),
  ('Bleu de Bresse', 'Fromage'),
  ('Chaource', 'Fromage'),
  ('Pont-l''Évêque', 'Fromage'),
  ('Reblochon', 'Fromage'),
  ('Morbier', 'Fromage'),
  ('Beaufort', 'Fromage'),
  ('Tomme de Savoie', 'Fromage'),
  ('Roquefort Société', 'Fromage'),
  ('Chèvre chaud', 'Fromage'),
  ('Saint-Nectaire', 'Fromage'),
  ('Marbré de chèvre', 'Fromage'),
  ('Raclette fumée', 'Fromage'),
  ('Fourme d''Ambert', 'Fromage'),
  ('Livarot', 'Fromage'),
  ('Cantal', 'Fromage'),
  ('Mont d''Or', 'Fromage'),
  ('Roquefort Papillon', 'Fromage'),
  ('Lait de vache', 'Lait'),
  ('Lait de chèvre', 'Lait'),
  ('Lait de brebis', 'Lait'),
  ('Lait d''amande', 'Lait'),
  ('Lait de soja', 'Lait'),
  ('Lait de coco', 'Lait'),
  ('Lait de riz', 'Lait'),
  ('Lait d''avoine', 'Lait'),
  ('Lait de noisette', 'Lait'),
  ('Lait de chanvre', 'Lait'),
  ('Lait de macadamia', 'Lait'),
  ('Lait de quinoa', 'Lait'),
  ('Lait de tigernut', 'Lait'),
  ('Lait de kamut', 'Lait'),
  ('Lait de bufflonne', 'Lait'),
  ('Crème fraîche', 'Crème'),
  ('Crème aigre', 'Crème'),
  ('Crème fouettée', 'Crème'),
  ('Crème épaisse', 'Crème'),
  ('Crème légère', 'Crème'),
  ('Crème double', 'Crème'),
  ('Crème liquide', 'Crème'),
  ('Crème de coco', 'Crème'),
  ('Crème de noisette', 'Crème'),
  ('Crème de cajou', 'Crème'),
  ('Crème de vanille', 'Crème'),
  ('Crème pâtissière', 'Crème'),
  ('Crème anglaise', 'Crème'),
  ('Crème de marron', 'Crème'),
  ('Crème de citron', 'Crème'),
  ('Beurre doux', 'Beurre'),
  ('Beurre salé', 'Beurre'),
  ('Beurre demi-sel', 'Beurre'),
  ('Beurre clarifié', 'Beurre'),
  ('Beurre d''ail', 'Beurre'),
  ('Beurre de cacahuète', 'Beurre'),
  ('Beurre d''amande', 'Beurre'),
  ('Beurre de noix de coco', 'Beurre'),
  ('Beurre de noisette', 'Beurre'),
  ('Beurre de karité', 'Beurre'),
  ('Sucre blanc', 'Sucre'),
  ('Sucre brun', 'Sucre'),
  ('Sucre glace', 'Sucre'),
  ('Sucre vanillé', 'Sucre'),
  ('Sucre de canne', 'Sucre'),
  ('Sucre cassonade', 'Sucre'),
  ('Sucre perlé', 'Sucre'),
  ('Sucre complet', 'Sucre'),
  ('Sucre muscovado', 'Sucre'),
  ('Sucre de palme', 'Sucre'),
  ('Sucre de coco', 'Sucre'),
  ('Sucre d''érable', 'Sucre'),
  ('Sucre de fleur de coco', 'Sucre'),
  ('Sucre de datte', 'Sucre'),
  ('Sucre de raisin', 'Sucre'),
 ('Pois chiche', 'Pois'),
  ('Pois vert', 'Pois'),
  ('Pois sec', 'Pois'),
  ('Pois gourmand', 'Pois'),
  ('Pois mangetout', 'Pois'),
  ('Pois cassé', 'Pois'),
  ('Pois lisse', 'Pois'),
  ('Pois à écosser', 'Pois'),
  ('Pois marbre', 'Pois'),
  ('Pois pigeon', 'Pois'),
  ('Pois sucré', 'Pois'),
  ('Pois noir', 'Pois'),
  ('Pois rouge', 'Pois'),
  ('Pois à gratter', 'Pois'),
  ('Pois fourrager', 'Pois'),
  ('Pois tarbais', 'Pois'),
  ('Pois du cap', 'Pois'),
  ('Pois de senteur', 'Pois'),
  ('Pois d''Angole', 'Pois'),
  ('Pois arborescent', 'Pois'),
  ('Miel d''acacia', 'Miel'),
  ('Miel de lavande', 'Miel'),
  ('Miel de thym', 'Miel'),
  ('Miel de manuka', 'Miel'),
  ('Miel de sarrasin', 'Miel'),
  ('Miel de châtaignier', 'Miel'),
  ('Miel d''eucalyptus', 'Miel'),
  ('Miel de fleurs sauvages', 'Miel'),
  ('Miel de trèfle', 'Miel'),
  ('Miel de citronnier', 'Miel'),
  ('Miel', 'Miel'),
 ('Jus d''orange', 'Jus'),
  ('Jus de pomme', 'Jus'),
  ('Jus de raisin', 'Jus'),
  ('Jus de tomate', 'Jus'),
  ('Jus de cranberry', 'Jus'),
  ('Jus de pamplemousse', 'Jus'),
  ('Jus d''ananas', 'Jus'),
  ('Jus de mangue', 'Jus'),
  ('Jus de citron', 'Jus'),
  ('Jus de poire', 'Jus'),
  ('Jus de cerise', 'Jus'),
  ('Jus de fraise', 'Jus'),
  ('Jus de grenade', 'Jus'),
  ('Jus d''abricot', 'Jus'),
  ('Jus de prune', 'Jus'),
  ('Jus de carotte', 'Jus'),
  ('Jus de pêche', 'Jus'),
  ('Jus de framboise', 'Jus'),
  ('Jus de myrtille', 'Jus'),
  ('Jus de kiwi', 'Jus'),
  ('Jus de melon', 'Jus'),
  ('Jus de pastèque', 'Jus'),
  ('Jus de papaye', 'Jus'),
  ('Jus de citron vert', 'Jus'),
  ('Jus de canneberge', 'Jus'),
  ('Jus de goyave', 'Jus'),
  ('Jus de cassis', 'Jus'),
  ('Jus de figue', 'Jus'),
  ('Jus de nectarine', 'Jus'),
  ('Jus de citronnelle', 'Jus'),
  ('Jus de curcuma', 'Jus'),
  ('Jus d''aloe vera', 'Jus'),
  ('Jus de concombre', 'Jus'),
  ('Jus de kale', 'Jus'),
  ('Jus de betterave', 'Jus'),
  ('Jus d''épinard', 'Jus'),
  ('Jus d''aloès', 'Jus'),
  ('Jus de chou frisé', 'Jus'),
  ('Jus de céleri', 'Jus'),
  ('Jus de gingembre', 'Jus'),
  ('Jus de menthe', 'Jus'),
  ('Jus de basilic', 'Jus'),
  ('Jus de persil', 'Jus'),
  ('Jus de pissenlit', 'Jus'),
  ('Jus de radis', 'Jus'),
  ('Jus de sapin', 'Jus'),
  ('Vin rouge', 'Vin'),
  ('Vin blanc', 'Vin'),
  ('Vin rosé', 'Vin'),
  ('Vin effervescent', 'Vin'),
  ('Vin doux', 'Vin'),
  ('Vin sec', 'Vin'),
  ('Vin moelleux', 'Vin'),
  ('Vin tranquille', 'Vin'),
  ('Vin pétillant', 'Vin'),
  ('Vin mousseux', 'Vin'),
  ('Blé dur', 'Blé'),
  ('Blé tendre', 'Blé'),
  ('Blé noir', 'Blé'),
  ('Blé à grains nus', 'Blé'),
  ('Blé à grains vêtus', 'Blé'),
  ('Blé Khorasan', 'Blé'),
  ('Blé Einkorn', 'Blé'),
  ('Blé Emmer', 'Blé'),
  ('Blé Kamut', 'Blé'),
  ('Blé spelt', 'Blé'),
  ('Blé Triticale', 'Blé'),
  ('Blé Rouge de Bordeaux', 'Blé'),
  ('Blé Rouge de Roumanie', 'Blé'),
  ('Blé Rouge de Bordeaux', 'Blé'),
  ('Blé Noir de Hollande', 'Blé'),
  ('Riz blanc', 'Riz'),
  ('Riz brun', 'Riz'),
  ('Riz sauvage', 'Riz'),
  ('Riz basmati', 'Riz'),
  ('Riz jasmin', 'Riz'),
  ('Riz gluant', 'Riz'),
  ('Riz Arborio', 'Riz'),
  ('Riz Carnaroli', 'Riz'),
  ('Riz noir', 'Riz'),
  ('Riz rouge', 'Riz'),
  ('Riz thaï', 'Riz'),
  ('Riz à grains courts', 'Riz'),
  ('Riz à grains longs', 'Riz'),
  ('Riz à sushi', 'Riz'),
  ('Riz parfumé', 'Riz'),
    ('Café arabica', 'Café'),
  ('Café robusta', 'Café'),
  ('Café liberica', 'Café'),
  ('Café excelsa', 'Café'),
  ('Café colombien', 'Café'),
  ('Café éthiopien', 'Café'),
  ('Café brésilien', 'Café'),
  ('Café guatémaltèque', 'Café'),
  ('Café jamaïcain', 'Café'),
  ('Café péruvien', 'Café'),
  ('Thé noir', 'Thé'),
  ('Thé vert', 'Thé'),
  ('Thé blanc', 'Thé'),
  ('Thé oolong', 'Thé'),
  ('Thé jaune', 'Thé'),
  ('Thé pu-erh', 'Thé'),
  ('Thé au jasmin', 'Thé'),
  ('Thé Earl Grey', 'Thé'),
  ('Thé Darjeeling', 'Thé'),
  ('Thé matcha', 'Thé'),
  ('Noix de cajou', 'Noix'),
  ('Noix de pécan', 'Noix'),
  ('Noix de macadamia', 'Noix'),
  ('Noix de Grenoble', 'Noix'),
  ('Noisettes', 'Noix'),
  ('Amandes', 'Noix'),
  ('Noix du Brésil', 'Noix'),
  ('Noix de coco', 'Noix'),
  ('Noix de pin', 'Noix'),
  ('Noix d''Amazonie', 'Noix'),
  ('Noix de karité', 'Noix'),
  ('Noix de muscade', 'Noix'),
  ('Noix de cola', 'Noix'),
  ('Noix de caryer', 'Noix'),
  ('Noix de tigernut', 'Noix'),
  ('Noix de cèdre', 'Noix'),
  ('Noix de Kola', 'Noix'),
  ('Noix de pécan', 'Noix'),
  ('Noix de para', 'Noix'),
  ('Noix de sapin', 'Noix'),
 ('Graines de tournesol', 'Graines'),
  ('Graines de citrouille', 'Graines'),
  ('Graines de lin', 'Graines'),
  ('Graines de chia', 'Graines'),
  ('Graines de sésame', 'Graines'),
  ('Graines de pavot', 'Graines'),
  ('Graines de courge', 'Graines'),
  ('Graines de chanvre', 'Graines'),
  ('Graines de moutarde', 'Graines'),
  ('Graines de tournesol', 'Graines'),
  ('Graines de melon', 'Graines'),
  ('Graines de grenade', 'Graines'),
  ('Graines de fenouil', 'Graines'),
  ('Graines de cumin', 'Graines'),
  ('Graines de carvi', 'Graines'),
  ('Yaourt nature', 'Yaourt'),
  ('Yaourt à la vanille', 'Yaourt'),
  ('Yaourt aux fruits rouges', 'Yaourt'),
  ('Yaourt aux fraises', 'Yaourt'),
  ('Yaourt aux framboises', 'Yaourt'),
  ('Yaourt aux myrtilles', 'Yaourt'),
  ('Yaourt à la pêche', 'Yaourt'),
  ('Yaourt à la mangue', 'Yaourt'),
  ('Yaourt à la noix de coco', 'Yaourt'),
  ('Yaourt à la banane', 'Yaourt'),
  ('Yaourt grec nature', 'Yaourt'),
  ('Yaourt grec à la vanille', 'Yaourt'),
  ('Yaourt grec aux fruits rouges', 'Yaourt'),
  ('Yaourt bulgare nature', 'Yaourt'),
  ('Yaourt à boire à la fraise', 'Yaourt'),
  ('Oeuf de poule', 'Oeuf'),
  ('Oeuf de caille', 'Oeuf'),
  ('Oeuf d''oie', 'Oeuf'),
  ('Oeuf de canard', 'Oeuf'),
  ('Oeuf de dinde', 'Oeuf'),
   ('Saumon', 'Poisson'),
  ('Thon', 'Poisson'),
  ('Maquereau', 'Poisson'),
  ('Sole', 'Poisson'),
  ('Tilapia', 'Poisson'),
  ('Morue', 'Poisson'),
  ('Merlan', 'Poisson'),
  ('Bar', 'Poisson'),
  ('Brochet', 'Poisson'),
  ('Poisson-chat', 'Poisson'),
  ('Carpe', 'Poisson'),
  ('Perche', 'Poisson'),
  ('Hareng', 'Poisson'),
  ('Anchois', 'Poisson'),
  ('Mulet', 'Poisson'),
  ('Crevettes', 'Fruit de mer'),
  ('Moules', 'Fruit de mer'),
  ('Palourdes', 'Fruit de mer'),
  ('Homard', 'Fruit de mer'),
  ('Crabe', 'Fruit de mer'),
  ('Calmar', 'Fruit de mer'),
  ('Coquilles Saint-Jacques', 'Fruit de mer'),
  ('Huîtres', 'Fruit de mer'),
  ('Langoustine', 'Fruit de mer'),
  ('Bulot', 'Fruit de mer');
    '''
  ];
}